run:
  deadline: 5m
  tests: false
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gocognit
    - gomnd
    - wsl
    - funlen
    - godox
    - goerr113
    - exhaustive
    - nestif
    - gofumpt
    - goconst
    - exhaustivestruct
    - wrapcheck
    - gci
    - godot
    - cyclop # TODO: add it back
linters-settings:
  nlreturn:
    # size of the block (including return statement that is still "OK")
    # so no return split required.
    block-size: 2
