repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: check-added-large-files
  - id: no-commit-to-branch
    args: [--pattern, 'v[0-9]+']

- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    # TODO: add it back
    # - id: go-cyclo
    #   args: [-over=15]
    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
      args: [--config, .golangci.yaml, --fix]
    - id: go-build
    - id: go-mod-tidy
