name: Go

on:
  push:
    branches: [master, v12]
  pull_request:
    branches: [master, v12]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        pg-version: [9, 10, 11, 12, 13, 14]

    services:
      postgres:
        image: postgres:${{ matrix.pg-version }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python2 for pre-commit
        uses: actions/setup-python@v2

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Install tomlv
        run: go install github.com/BurntSushi/toml/cmd/tomlv@master

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1

      - name: pre-commit
        uses: pre-commit/action@v2.0.3

      - name: Install hstore
        run: PGPASSWORD=postgres psql -U postgres -h localhost -c "CREATE EXTENSION hstore"

      - name: Test
        run: make test
